---
- hosts: localhost
  vars:
    hello: "{{ morpheus["customOptions"]["foo"] }}"

  tasks:
    - blockinfile:
        create: yes
        path: "/tmp/testout.txt"
        block: |
          {{ hello }}
