---
- hosts: localhost
  vars:
    hello: "{{ morpheus['results']['foo'] }}"

  tasks:
    - pause: minutes=1
    - blockinfile:
        create: yes
        path: "/tmp/testout.txt"
        block: |
          {{ hello }}
